import type { Metadata } from "next";
import AuthSessionProvider from "@/components/session-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <AuthSessionProvider>{children}</AuthSessionProvider>
            </body>
        </html>
    );
}
